name: SSH to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-76-106-239.eu-central-1.compute.amazonaws.com
          username: ubuntu  # Use the correct username for your EC2 instance
          port: 22  # Use the correct SSH port if necessary
          script: |
            # Run your desired SSH command here
            # For example, echoing a message:
            echo "Hello from GitHub Actions!"
